Table users {
  id            integer [primary key, increment]
  username      varchar(64) [not null, unique]
  email         varchar(256) [not null, unique]
  password_hash varchar(256) [not null]
}

Table matches {
  id          integer [primary key, increment]
  played_at   timestamp [not null, default: `now()`]
  season      integer [not null]
  att_black   integer [not null]
  att_white   integer [not null]
  def_black   integer [not null]
  def_white   integer [not null]

  indexes {
    (played_at) [unique, name: 'ix_matches_played_at']
  }
}

Table results {
  id                integer [primary key, increment]
  match_id          integer [not null]
  created_at        timestamp [not null, default: `now()`]
  created_by        integer [not null]
  checked_at        timestamp [null]
  checked_by        integer [null]
  status            varchar(64) [not null]
  score_black       integer [not null]
  score_white       integer [not null]
  klinker_att_black integer [not null]
  klinker_att_white integer [not null]
  klinker_def_black integer [not null]
  klinker_def_white integer [not null]
  keeper_black      integer [not null]
  keeper_white      integer [not null]

  indexes {
    (created_at) [name: 'ix_results_created_at']
    (match_id) [unique, name: 'uq_results_match']
  }
}

Table ratings {
  id                     integer [primary key, increment]
  user_id                integer [not null]
  match_id               integer [null]
  since                  timestamp [not null, default: `now()`]
  season                 integer [not null]
  previous_rating        integer [null]
  rating                 integer [not null]
  previous_rating_season integer [null]
  rating_season          integer [null]

  indexes {
    (since) [name: 'ix_ratings_since']
    (user_id, match_id) [unique, name: 'uq_ratings_user_match']
  }
}

Ref: matches.att_black > users.id
Ref: matches.att_white > users.id
Ref: matches.def_black > users.id
Ref: matches.def_white > users.id

Ref: results.match_id - matches.id
Ref: results.created_by > users.id
Ref: results.checked_by >? users.id

Ref: ratings.user_id > users.id
Ref: ratings.match_id >? matches.id