"""add season columns

Revision ID: 589cbe5d3ebc
Revises: eea76646b5ce
Create Date: 2024-04-15 21:05:28.567116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589cbe5d3ebc'
down_revision = 'eea76646b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previous_rating_season', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_season', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('rating_season')
        batch_op.drop_column('previous_rating_season')
        batch_op.drop_column('season')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('season')

    # ### end Alembic commands ###
