"""empty message

Revision ID: 8ee6f8db648b
Revises: e65f183ebfd6
Create Date: 2023-12-10 16:40:44.936145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee6f8db648b'
down_revision = 'e65f183ebfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings_att',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_att', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_att_since'), ['since'], unique=False)

    op.create_table('ratings_def',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_def', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_def_since'), ['since'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings_def', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_def_since'))

    op.drop_table('ratings_def')
    with op.batch_alter_table('ratings_att', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_att_since'))

    op.drop_table('ratings_att')
    # ### end Alembic commands ###
