"""remove rating_att and rating_def

Revision ID: eea76646b5ce
Revises: 3c09c9764288
Create Date: 2024-04-15 20:51:05.017977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea76646b5ce'
down_revision = '3c09c9764288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings_def', schema=None) as batch_op:
        batch_op.drop_index('ix_ratings_def_since')

    op.drop_table('ratings_def')
    with op.batch_alter_table('ratings_att', schema=None) as batch_op:
        batch_op.drop_index('ix_ratings_att_since')

    op.drop_table('ratings_att')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings_att',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('since', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('previous_rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_att', schema=None) as batch_op:
        batch_op.create_index('ix_ratings_att_since', ['since'], unique=False)

    op.create_table('ratings_def',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('since', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('previous_rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_def', schema=None) as batch_op:
        batch_op.create_index('ix_ratings_def_since', ['since'], unique=False)

    # ### end Alembic commands ###
